### ISSUE TITLE
AppConfig allows invalid JSON

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-core#109]
You can add a JSON config with the value `['fooBar']` - note the single quotes.  The Grails server will validate and save this value, but the browser will choke when attempting to parse.

(I ran into this when I attempted to use the config differ where I had this bad JSON config locally.)

**Comment by peterjcoffman** [comment]
Rather than trying to more strictly validate user input, it might be better to generate fresh JSON on the server. We could store `JSON.parse(value).toString(true)` as our config. This would be lenient on the user while still storing things in a canonical form. Plus, it would make formatting consistent.

**Comment by lbwexler** [comment]
👍
