### ISSUE TITLE
Ensure there is a way to adjust maxPostSize for the Admin app

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-core#238]
Some client apps display a lot of data in the Admin panel, either in the Activity grids because of heavy use, or in custom app specific grids that are for Admins only.
These apps are already given memory allocations that support large data sets, so they would be able to support exporting data that is larger than 20MB from their Admin panel.

We have run into a problem however, in which the usual "switches" that we use in an app to raise the maxPostSize limit are not being applied to the Admin app. They are applied to just the user facing app.

This problem was discovered on our legacy Hoist-Core (grails 3.3.9).
We should confirm that our latest version of Hoist-Core (grails 5.x) exposes levers that allows maxPostSize to be adjusted for the Admin app as well.

**Comment by amcclain** [comment]
I can't think of any reason why the admin app would be any different in this regard - it's a purely client-side construct, and it sounds like it's the shared grid export endpoint where you are hitting this limit, which is used consistently across both client admin and business-facing grids. 

The server doesn't know or care which JS app / model is posting grid data for processing. I would expect both hoist-core and app-specific endpoints to have the same limits enforced by the overall container (Tomcat) - but even if there were a difference between the plugin controllers and app controllers, that doesn't sound like what is going on here with grid exports.

As always, these max POST size limits can occur at a few levels - Grails, Tomcat, our Hoist nginx proxy, and finally any ingress or gateway/load balancer (e.g. in Rancher/k8s world). But the same caveat should apply to all of those - no reason why a call to the grid export endpoint would differ from one JS app to the next, as far as I can imagine.

I believe some more testing is required to understand the real issue here. :thinking:

**Comment by cnrudd** [comment]
I've been testing on a local instance of toolbox with the grails 5 code, and found that we were missing one setting to enable our stated goal of [supporting 20mb exports by default](https://github.com/xh/hoist-core/blob/develop/src/main/groovy/io/xh/hoist/configuration/ApplicationConfig.groovy#L66).

So here is a pull request to fix that:
https://github.com/xh/hoist-core/pull/240


As you say @amcclain , these settings do apply to both the Admin and main app, so the error we are seeing in the admin section of our client app must be coming from some other config in the production setup:  nginx, rancher, k8s.  Haven't figured out where yet.

**Comment by lbwexler** [comment]
Closing this ticket, as it seems specifically about the admin app, being somehow different from other apps, which we no longer think is the case.  Discussion is ongoing about the correct default limits of course
